### ISSUE TITLE
Excessive use of maps

### ISSUE THREAD

**Issue by rdumont** [vtex/findhelp#4]
From doing the PR #3 and dealing a little bit with the library, I perceived one core problem, which is the use of maps everywhere. Maps, as we know, shouldn't have any order for their keys and values. That made me do a bit of a hack to get the namespace command represented before all others, and I believe more problems may arise from it.

So here I suggest that we switch from a map-based structure to arrays, switching from:

``` js
const tree = {
  list: {
    description: 'List apps',
    handler: () => {}
  },
  settings: {
    description: 'Get settings',
    handler: () => {},

    set: {
      description: 'Set settings value',
      handler: () => {}
    },
    unset: {
      description: 'Unset settings value',
      handler: () => {}
    }
  }
}
```

To:

``` js
const tree = [
  {
    name: 'list',
    description: 'List apps',
    handler: () => {}
  },
  {
    name: 'settings',
    description: 'Get settings',
    handler: () => {},
    children: [
      {
        name: 'set',
        description: 'Set settings value',
        handler: () => {}
      },
      {
        name: 'unset',
        description: 'Unset settings value',
        handler: () => {}
      },
    ]
  }
]
```

Yes, I know it is not as pretty, but I think it is clearer, of easier maintenance and less error-prone. For instance, ambiguity between a field and a command name would never be an issue.

@firstdoit, @tamorim, what do you think?

**Comment by vibegui** [comment]
The idea for this library is to be fluent and fit the JS paradigm allowing you to compose commands as a simple object tree. That's _why_ I created this in the first place. 😃

By the way, objects _are_ indeed ordered according to the spec, with the exception of "integer indexes": https://tc39.github.io/ecma262/#sec-ordinaryownpropertykeys

And, practically speaking, Node runs on V8, and V8 respects the creation order, so that shouldn't be a problem in the foreseeable future. If they change that, half the internet will 💥.

Regarding ambiguity: there is no such thing. If a node has a `handler`, it's a command.

So, seeing as this would compromise the core concept of the library, I'd rather that we didn't change this style.

**Comment by rdumont** [comment]
Awesome, no problem! I really had no idea that the spec described ordered properties in objects. And, now that you mentioned, they are in fact `Object`s, not `Map`s.

About the ambiguity, I'll rephrase, because that's not what I meant. I meant that, for instance, I can't have a namespace with its own handler and a command called `description`, because that would be mistaken for the own namespace's description. But I guess that is an issue apart from this one.
